FROM java:8
LABEL maintainer=“01114831@pw.edu.pl”
VOLUME /tmp
EXPOSE 8080
ADD ./target/populator-0.0.1-SNAPSHOT.jar populator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","populator-0.0.1-SNAPSHOT.jar"]

