FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Scrapper/Scrapper.csproj", "Scrapper/"]
RUN dotnet restore "Scrapper/Scrapper.csproj"
COPY . .
WORKDIR "/src/Scrapper"
RUN dotnet build "Scrapper.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Scrapper.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Scrapper.dll"]

