FROM rust:latest as build

COPY ./ ./

RUN cargo build --release
RUN mkdir -p /build-out
RUN cp target/release/szaklon-api /build-out/

FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y libssl-dev
RUN apt-get install -y sqlite3

COPY --from=build /db.sqlite /
COPY --from=build /config.toml /
COPY --from=build /build-out/szaklon-api /

CMD /szaklon-api

